export const categories = [
  { name: 'Дизайн и Арт', color: 'bg-[#EEF1FF]', icon: '🎨', slug: 'graphics-design' },
  { name: 'Программирование', color: 'bg-[#F0F9FF]', icon: '💻', slug: 'programming' },
  { name: 'Искусственный интеллект', color: 'bg-[#F5F3FF]', icon: '🤖', slug: 'ai' },
  { name: 'Тексты и Переводы', color: 'bg-[#FFFBEB]', icon: '✍️', slug: 'writing' },
  { name: 'Маркетинг и SEO', color: 'bg-[#FFF1F2]', icon: '📈', slug: 'marketing' },
  { name: 'Бизнес и Услуги', color: 'bg-[#ECFDF5]', icon: '💼', slug: 'business' },
  { name: 'Видео и Аудио', color: 'bg-[#FFF7ED]', icon: '🎬', slug: 'video' },
  { name: 'Фотография', color: 'bg-[#F0FDFA]', icon: '📸', slug: 'photography' },
];

export const specialists = [
  {
    id: 'specialist-1',
    name: 'Елена Макарова',
    role: 'UI/UX Дизайнер',
    earned: '1.5M ₸',
    earnedValue: 1500000,
    projects: 86,
    rating: 4.9,
    reviews: 124,
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['Figma', 'Product Design', 'Mobile'],
    description: 'Создаю дизайн-системы и интерфейсы, которые влюбляют пользователей в ваш продукт.',
    status: 'Verified Pro',
    experience: 'Senior',
    paymentType: 'Фиксированная',
    city: 'Алматы'
  },
  {
    id: 'specialist-2',
    name: 'Арман Сериков',
    role: 'Full-stack Разработчик',
    earned: '3.2M ₸',
    earnedValue: 3200000,
    projects: 41,
    rating: 5.0,
    reviews: 52,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    description: 'Разработка архитектуры и фронтенда для сложных веб-приложений и стартапов.',
    status: 'Top Rated',
    experience: 'Expert',
    paymentType: 'Почасовая',
    city: 'Астана'
  },
  {
    id: 'specialist-3',
    name: 'Мадина Кумар',
    role: 'AI Консультант',
    earned: '800K ₸',
    earnedValue: 800000,
    projects: 15,
    rating: 4.8,
    reviews: 31,
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['Python', 'ChatGPT', 'Automation'],
    description: 'Внедрение ИИ в бизнес-процессы для автоматизации и снижения затрат.',
    status: 'Verified',
    experience: 'Middle',
    paymentType: 'Фиксированная',
    city: 'Дистанционно'
  },
  {
    id: 'specialist-4',
    name: 'Тимур Ибраев',
    role: 'SMM Менеджер',
    earned: '2.1M ₸',
    earnedValue: 2100000,
    projects: 64,
    rating: 4.7,
    reviews: 89,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['Instagram', 'Ads', 'Strategy'],
    description: 'Продвижение брендов в соцсетях с фокусом на целевые лиды и узнаваемость.',
    status: 'Top Rated',
    experience: 'Senior',
    paymentType: 'Почасовая',
    city: 'Алматы'
  },
  {
    id: 'specialist-5',
    name: 'Данияр Ахметов',
    role: 'Python Developer',
    earned: '1.2M ₸',
    earnedValue: 1200000,
    projects: 28,
    rating: 4.6,
    reviews: 45,
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['Django', 'FastAPI', 'ML'],
    description: 'Разработка высокопроизводительных бэкендов и интеграция нейросетей.',
    status: 'Verified',
    experience: 'Middle',
    paymentType: 'Фиксированная',
    city: 'Астана'
  },
  {
    id: 'specialist-6',
    name: 'Алия Бекмамбетова',
    role: 'Graphic Designer',
    earned: '1.8M ₸',
    earnedValue: 1800000,
    projects: 112,
    rating: 5.0,
    reviews: 210,
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200&h=200',
    tags: ['Illustrator', 'Branding', 'Vector'],
    description: 'Создание уникального визуального языка для брендов международного уровня.',
    status: 'Verified Pro',
    experience: 'Expert',
    paymentType: 'Фиксированная',
    city: 'Дистанционно'
  }
];

export const jobs = [
  {
    id: 1,
    title: 'Разработка мобильного приложения для доставки еды (iOS/Android)',
    client: 'FoodExpress Ltd.',
    budget: '750,000 ₸',
    type: 'Фиксированная цена',
    posted: '2 часа назад',
    experience: 'Expert',
    description: 'Мы ищем опытного Full-stack разработчика для создания MVP приложения доставки. Необходим опыт работы с Flutter или React Native. Бэкенд на Node.js или Python.',
    tags: ['Mobile Development', 'Flutter', 'API Integration'],
    verified: true,
    location: 'Алматы',
    deadline: '30 дней'
  },
  {
    id: 2,
    title: 'Дизайн логотипа и фирменного стиля для строительной компании',
    client: 'BuildKz',
    budget: '150,000 ₸',
    type: 'Проект',
    posted: '5 часов назад',
    experience: 'Intermediate',
    description: 'Нужен современный, минималистичный логотип, подчеркивающий надежность. В пакет должен входить брендбук и дизайн визиток.',
    tags: ['Logo Design', 'Branding', 'Adobe Illustrator'],
    verified: false,
    location: 'Дистанционно',
    deadline: '10 дней'
  },
  {
    id: 3,
    title: 'Настройка рекламных кампаний в Google & Meta',
    client: 'Global Shop',
    budget: '45,000 ₸ / месяц',
    type: 'Почасовая',
    posted: '1 день назад',
    experience: 'Junior+',
    description: 'Требуется специалист по таргетированной рекламе для интернет-магазина одежды. Бюджет на рекламу обсуждается отдельно.',
    tags: ['Digital Marketing', 'Facebook Ads', 'Google Ads'],
    verified: true,
    location: 'Астана',
    deadline: 'На постоянной основе'
  }
];
